version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - mongodb:/data/db
    ports: 
      - "27017:27017"
    networks:
      - api_plano_alimentar
  api:
    container_name: api-container
    depends_on:
      - mongo
    build: .
    image: plano-alimentar
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/plano-alimentar/dist
      - ./package.json:/usr/src/plano-alimentar/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongo
    networks:
      - api_plano_alimentar

networks:
  api_plano_alimentar:

volumes:
  mongodb:
