version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      "27017:27017"
  api:
    depends_on:
    - mongo
    container_name: api-container
    build: .
    image: plano_alimentar
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/plano_alimentar/dist
    ports:
      - "5050:5050"
    links: 
      - mongo