name: Teste do Projeto

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

jobs:
  tests: 
    name: Executar Testes Unitários
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: ["20.x"]
    steps: 
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Instalar Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cachear Módulos Node
        uses: actions/cache@v3
        with:
          path: ~/npm 
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar Dependências
        run: npm ci

      - name: Testes unitários
        run: npm run test:all
        
