name: Teste do Projeto

on:
  push:
    branches:
      - main

jobs:
  teste: 
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: ["20.x"]
    steps: 
      - name: Baixar repositório
        uses: actions/checkout@v4
      - name: Instalar Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instalar Dependências
        run: npm ci
      - name: Testes unitários
        run: npm run test:all
        
